spring:
  data:
    mongodb:
      uri: "mongodb+srv://admin:admin@demo.uskpz.mongodb.net/sample_mflix"
      host: localhost
      port: 27017
      database: sample_mflix
      username: admin
      password: admin
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
jwt:
  secret: sSjVnDloGP3NnL5GVCFn5xLzhWm0IGcC
  token:
    validity: 86400000